---

- name: Ensure vb apt packages present
  apt:
    name: virtualbox-guest-utils
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: install upgrade
  apt: upgrade=dist
  register: ug_complete

- name: reboot the system
  command: /sbin/reboot
  ignore_errors: true
  when: ug_complete.changed

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started search_regex=OpenSSH
  sudo: false

- name: Wait for SSH to come up
  wait_for:
    host: "{{ host_ip }}"
    port: 22
    delay: 60
    timeout: 120
    state: started
  when: ug_complete.changed
