---

- name: install dnsmasq
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - dnsmasq
    - avahi-daemon

- name: ensure dhcp config added
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    dest: "/etc/dnsmasq.conf"
  with_items:
    - line: "interface=br0"
      regexp: "^interface=br0$"
    - line: "dhcp-range=172.16.8.50,172.16.8.130,1h"
      regexp: "^dhcp-range=.*$"
  register: dnsmasq_config

- name: reboot the system
  command: /sbin/reboot
  ignore_errors: true
  when: dnsmasq_config.changed

- name: waiting for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started search_regex=OpenSSH
  sudo: false

- name: Wait for SSH to come up
  wait_for:
    host: "{{ host_ip }}"
    port: 22
    delay: 60
    timeout: 120
    state: started
  when: dnsmasq_config.changed